# Site settings
title: Cards Jekyll Template
description: Test Jekyll + Netlify
baseurl: # the subpath of your site, e.g. /blog
url: https://cranky-johnson-d17da0.netlify.app/ # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Lorem Ipsum
user_description: Anon Developer at Lorem Ipsum Dolor
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
# google_analytics: UA-129179896-1

# Enter your Google Webmaster Tools web tracking code (e.g. 2D5zbZ2Vatb8CeFj1cUCRdJZ3SQatSUlQesml02jEPo) to activate tracking
# google_verify: v3OZmTaPJYaCo3Jb_bgy1VrMyB3w5fKXZTTEP1eRgyw

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

comments: false
author: false

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Tags
    url: /tags
  - title: Archive
    url: /archive
  - title: About
    url: /about

# Sass config
sass:
  sass_dir: src/sass
  style: :compressed # You might prefer to minify using :compressed, default :expanded

paginate: 12
paginate_path: /page:num/

plugins:
  - jekyll-paginate

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
